#!/bin/sh

source ~/.bash/functions
source ~/.bash/paths
source ~/.bash/environmentvariables
source ~/.bash/aliases
source ~/.bash/virtualenvwrapperprompt
source ~/.bash/gitprompt
source ~/.bash/prompt
