set nocompatible
set bs=2
set laststatus=2
set ts=8 sts=4 sw=4 expandtab smarttab
set autoindent smartindent
set nowrap
set ignorecase smartcase incsearch
set scrolloff=999

map <f9> :w<CR>:!ipython -i %<CR>

" Show tab chars and trailing whitespace.
" Useful for cleaning up the slop left by Emacs users.
set list
set listchars=tab:>-,trail:-  "× ✖ • ● ▄ ■ ▐ ░ ▒ ▓ ▞ ┅ ━ ◀ ▶ ⋀ ⊥ ⎵ ⎶  ➜ ╳

autocmd BufRead *.py set nocindent nosmartindent autoindent

set wildmode=longest,list
set nu
set nostartofline   " Leave cursor in same column after page up/down.
set ruler
syntax on

command Killtrailingwhitespace :%s/\s\+$//g
