#!/bin/bash
# This hook is sourced after every virtualenv is activated.

if [ ${_OLD_VIRTUAL_PS1:0:2} == '\n' ]; then
    PS1="\n\[\e[1;33;45m\] (`basename \"$VIRTUAL_ENV\"`) \[\e[0m\] ${_OLD_VIRTUAL_PS1:2:${#_OLD_VIRTUAL_PS1}}"
else
    PS1="\[\e[1;33;45m\] (`basename \"$VIRTUAL_ENV\"`) \[\e[0m\] $_OLD_VIRTUAL_PS1"
fi
