#!/bin/sh

# http://blog.doughellmann.com/2010/01/virtualenvwrapper-tips-and-tricks.html

# directory creation really belongs in premkvirtualenv but rather DRY and see the error message on creation.
coderoot="$HOME/code"
project="${ACTIVE_VIRTUALENV%%-*}"
codedir="$coderoot/$project"

echo "Creating directory: $codedir..."
mkdir $codedir
add2virtualenv $codedir
cd $codedir

echo "Upgrading setuptools and installing pip..."
easy_install -U setuptools && easy_install pip

# snow leopard + libedit + ipython = broken line editing
# use readline
if [ "$(uname -s)" == "Darwin" ]; then
    # currently doesn't work with pip, for reasons unknown
    easy_install readline
fi
